var lData = [{
	'name': '人大',
	'hotels': []
}, {
	'name': '政协',
	'hotels': [{
		'name': '京西宾馆',
		'groups': [{
			'name': '中华全国台湾同胞联谊会',
			'count': 14,
			'date': '3月2日',
			'male': 8,
			'people': [{
				name: '江尔雄',
				race: null,
				sex: '女',
				prov: null
			}, {
				name: '李大壮',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '杨毅周',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '肖燚',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '张百良',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '陈建华',
				race: '高山族',
				sex: '女',
				prov: null
			}, {
				name: '林娜',
				race: null,
				sex: '女',
				prov: null
			}, {
				name: '郑平',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '姚志胜',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '凌友诗',
				race: null,
				sex: '女',
				prov: null
			}, {
				name: '高峰',
				race: null,
				sex: null,
				prov: '北京'
			}, {
				name: '黄兰茜',
				race: null,
				sex: '女',
				prov: null
			}, {
				name: '曾鲁台',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '颜珂',
				race: null,
				sex: '女',
				prov: null
			}]
		}, {
			'name': '中华全国青年联合会',
			'count': 28,
			'date': '3月4日',
			'male': 21,
			'people': [{
				name: '马全林',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '马海军',
				race: '回族',
				sex: null,
				prov: null
			}, {
				name: '王小川',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '王煜宇',
				race: null,
				sex: '女',
				prov: null
			}, {
				name: '田静',
				race: null,
				sex: '女',
				prov: null
			}, {
				name: '冯艺东',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '朱妍',
				race: null,
				sex: '女',
				prov: null
			}, {
				name: '朱涛',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '刘屹',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '许礼进',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '李迎新',
				race: '满族',
				sex: '女',
				prov: null
			}, {
				name: '肖新光',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '吴杰庄',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '吴碧霞',
				race: null,
				sex: '女',
				prov: null
			}, {
				name: '张威',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '张红文',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '阿布都克力木·艾则孜',
				race: '维吾尔族',
				sex: null,
				prov: null
			}, {
				name: '其实',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '林积灿',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '郑春阳',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '施小明',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '敖刘全',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '谈剑锋',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '程静',
				race: null,
				sex: '女',
				prov: null
			}, {
				name: '曾芳',
				race: null,
				sex: '女',
				prov: null
			}, {
				name: '温涛',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '楼家强',
				race: null,
				sex: null,
				prov: null
			}, {
				name: '霍启刚',
				race: null,
				sex: null,
				prov: null
			}]
		}]
	}]
}]